### PR TITLE
Fixed Icons in explorer activity. #180

### PR DESCRIPTION
**Pull request by pg301**
Fixed Icons in explorer activity. #180

### CODE REVIEW

**Comment by KeenWarrior** [comment]
@pg301 Please add screenshots

**Comment by pg301** [comment]
screenshot_1492434275
screenshot_1492434330

**Comment by pg301** [comment]
@garg-anuj I have uploaded some screenshots. Please have a look at it.

**Review by KeenWarrior — APPROVED** [review]
:+1:

**Pull request merged**
