### PR TITLE
Update on #229

### PR DESCRIPTION
**Pull request by pg301**
screen shot 2017-07-04 at 11 22 33 pm

These changes will give the following output

### CODE REVIEW

**Comment by KeenWarrior** [comment]
@pg301 are you stuck?

**Comment by pg301** [comment]
@garg-anuj can you please help me in debugging.

**Comment by KeenWarrior** [comment]
@pg301 what is the issue you are facing?

**Comment by pg301** [comment]
@garg-anuj This is the API response https://paste.ubuntu.com/25037821/ and I am trying to decompress it. Somehow I am not able to get all the resources names. This is the decompressed response of the same API https://paste.ubuntu.com/25037833/

**Comment by pg301** [comment]
screenshot_1499438948

Finally it's close

**Comment by KeenWarrior** [comment]
@pg301 Looking good to me. Lemme merge it

**Review by KeenWarrior — APPROVED** [review]

**Pull request merged**
