### PR TITLE
Delete Trigger, Adding a metric to favourite fixed and added response messages

### PR DESCRIPTION
**Pull request by pg301**
screenshot_1501668350

In case trigger details are incorrect, the corresponding error message will be shown.

### CODE REVIEW

**Comment by pg301** [comment]
@garg-anuj Don't merge it as of now. I am also working on deleting a trigger from the client. Will push the corresponding code in this branch only,

**Comment by pg301** [comment]
Added Delete Trigger functionality 

deleterigger

**Comment by KeenWarrior** [comment]
@pg301 license header issue

**Comment by pg301** [comment]
add to favourite

@garg-anuj @pilhuhn This fixes add a metric to favourite issue.

**Comment by pg301** [comment]
@garg-anuj @pilhuhn Metric addition to favourite is now fixed. Please review.

**Comment by KeenWarrior** [comment]
@pg301 awesome work :tada:

**Review by KeenWarrior — APPROVED** [review]

**Pull request merged**
