### PR TITLE
Personas

### PR DESCRIPTION
**Pull request by arturdryomov**
There is an ability to choose a current persona. If there is a single persona available the chooser is hidden automagically. There is a deauthorization flow as well. Take a look at #34 and #26 if you are interested in motivation.

device-2015-07-28-153832
device-2015-07-28-154542
device-2015-07-28-154531
device-2015-07-28-154032

### CODE REVIEW

**Comment by pilhuhn** [comment]
Haven't tried it yet, but that certainly looks good and useful

**Comment by pilhuhn** [comment]
I don't see any metrics at all with that applied

**Comment by arturdryomov** [comment]
@pilhuhn, do you mean charts or just metrics, i. e. the list with Status Code and Response Time items?

**Comment by pilhuhn** [comment]
It says "nothing here - go to the UI to add some".  But it may be another master vs Alpha2 thingy

**Comment by arturdryomov** [comment]
@pilhuhn, I’ve tried it using [this snapshot](https://repository.jboss.org/nexus/content/repositories/snapshots/org/hawkular/hawkular-dist/1.0.0.Alpha3-SNAPSHOT/). Are there any URLs with more fresh snapshots?

**Comment by arturdryomov** [comment]
@pilhuhn, if it is possible please try Alpha 2 with it.

**Comment by arturdryomov** [comment]
@pilhuhn, can you please try again using `demo.hawkular.org` or Alpha 3 locally? Works for me, shows every screen fine.

**Comment by pilhuhn** [comment]
Works now for me as well

**Pull request merged**
