### PR TITLE
Token Activity and corresponding changes

### PR DESCRIPTION
**Pull request by openwarrior**
Token Activity is complete with add and remove operations
on tokens. For Navigation to this, menu item added in drawer.

### CODE REVIEW

**Comment by openwarrior** [comment]
Screen record/ of working is https://drive.google.com/file/d/0B8tYKC1-UERHQ2Q1MWhvbHM0akU/view?pref=2&pli=1

**Comment by danielpassos** [comment]
@anuj1708 I'll review your code Monday morning, anyway, I have seen the screencast. Very nice job!

**Comment by openwarrior** [comment]
@danielpassos  Thank you

**Comment by danielpassos** [comment]
:+1:

**Comment by danielpassos** [comment]
@anuj1708 Thanks for your contribution

**Comment by openwarrior** [comment]
@danielpassos  Thank you for your review and support :)

**Pull request merged**
