### PR TITLE
Make ViewDirector more fluent

### PR DESCRIPTION
**Pull request by danielpassos**
A little change to make ViewDirector more fluent and auto explain :)

@ming13 Feel free to merge it if you agree

### CODE REVIEW

**Comment by arturdryomov** [comment]
`ViewDirector` was named as a real-world analog. I needed some name for a class which will “supervise” `ViewAnimator` instances. Every movie, including animation ones, have directors. In other words API was set as a “the director of the animator will show the view”. Actually it sounds a bit weird.

I suggest a slightly modified version.

``` java
ViewDirector.of(activity)
  .using(R.id.animator)
  .show(R.id.view);
```

It can be read as “the director of the screen will show the view using the animator”.

**Comment by danielpassos** [comment]
@ming13 Done!

**Comment by arturdryomov** [comment]
Great! Feel free to merge, there will be conflicts.

**Comment by danielpassos** [comment]
Rebased!

**Pull request merged**
