### PR TITLE
Add tabs in Favourites and Alerts fragment

### PR DESCRIPTION
**Pull request by openwarrior**
- favourites now contain fav metrics and fav triggers
- Alerts now contain all alerts and all triggers
- fav triggers can be saved from all triggers

### CODE REVIEW

**Comment by openwarrior** [comment]
@danielpassos @pilhuhn Please review it :)

**Comment by pilhuhn** [comment]
@danielpassos Can you please take care here ?

@anuj1708 Can you attach a screenshot that shows changes or the situation after the PR?

**Comment by openwarrior** [comment]
@pilhuhn @danielpassos [Here is video link for changes](https://drive.google.com/file/d/0B8tYKC1-UERHZlh3YTloX0tybmc/view?usp=sharing)

**Comment by danielpassos** [comment]
@pilhuhn Sorry I already have tested it when it was in development helping @anuj1708 but forgot to merge

**Pull request merged**
