### PR TITLE
Icon in explorer activity fixed

### PR DESCRIPTION
**Pull request by anant-dev**
Fixed Issue #180 
Please review
Updated screen - 
screenshot_2017-03-22-08-55-24-516

### CODE REVIEW

**Comment by KeenWarrior** [comment]
@anant-dev Would love to see svg files instead

**Comment by anant-dev** [comment]
@garg-anuj ok i ll replace them by svg files

**Comment by anant-dev** [comment]
@garg-anuj Done please review

**Comment by KeenWarrior** [comment]
You will need to execute : mvn license:format

**Comment by anant-dev** [comment]
@garg-anuj done for issue #180  
and also resolved issue #187 by 5ed52795aef3f8092171f2e214dc261305b80a7f commit. Please review

**Comment by m-murad** [comment]
@anant-dev 
You have to to squash the commits before your PR is considered.
Also you shouldn't solve multiple issues in one PR. I did it earlier and was asked to update the PR.
If you are solving two issues send two PRs.

Regards

**Comment by KeenWarrior** [comment]
@anant-dev Please try not to solve more than one issue in one PR if they are not very much related

**Pull request closed without merging**
