### PR TITLE
new endpoints of keycloak and uris updated to hawkular/accounts

### PR DESCRIPTION
**Pull request by openwarrior**

### CODE REVIEW

**Comment by arturdryomov** [comment]
License plugin doesn’t like this. Just change year from `2015` to `2016` in headers of `BackendAuthorization.java` and `BackendPipes.java`, this should do the trick.

**Comment by jpkrohling** [comment]
Or use `mvn license:format` :)

**Comment by openwarrior** [comment]
Now it look all fine to me.
Please tell if any other change is to be made.

**Comment by pilhuhn** [comment]
@jpkrohling @danielpassos ?

**Comment by jpkrohling** [comment]
That looks OK to me, but I still can't build locally, so, I can't say if it works :)

**Comment by pilhuhn** [comment]
Thank you @anuj1708 :clap:

**Comment by openwarrior** [comment]
pleasure is all mine :)

**Pull request merged**
