### PR TITLE
Remove authorization activity

### PR DESCRIPTION
**Pull request by KeenWarrior**
Merge two classes used for login into one

### CODE REVIEW

**Comment by KeenWarrior** [comment]
@danielpassos we urgently needed these changes so took code from your branch and rebased. Please look into it and merge if look fine. We are stuck without merging it.

**Comment by KeenWarrior** [comment]
@pg301 can you also test and comment if this PR if it is working fine?

**Comment by pg301** [comment]
@garg-anuj I will also test and let you know the results.

**Comment by danielpassos** [comment]
I'm getting an error while trying to run the app. 

```
06-29 15:57:40.528 9192-9192/org.hawkular.client.android I/art: Late-enabling -Xcheck:jni
06-29 15:57:40.555 9192-9198/org.hawkular.client.android I/art: Debugger is no longer active
06-29 15:57:40.565 9192-9192/org.hawkular.client.android W/System: ClassLoader referenced unknown path: /data/app/org.hawkular.client.android-2/lib/arm
06-29 15:57:40.574 9192-9192/org.hawkular.client.android I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
06-29 15:57:40.595 9192-9192/org.hawkular.client.android W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
06-29 15:57:40.692 9192-9209/org.hawkular.client.android D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-29 15:57:41.037 9192-9192/org.hawkular.client.android I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
06-29 15:57:41.043 9192-9192/org.hawkular.client.android I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
06-29 15:57:41.046 9192-9192/org.hawkular.client.android I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
06-29 15:57:41.053 9192-9192/org.hawkular.client.android I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
06-29 15:57:41.074 9192-9192/org.hawkular.client.android W/SupportMenuInflater: Cannot instantiate class: android.support.v7.widget.SearchView
                                                                                java.lang.NoSuchMethodException: <init> [class android.content.Context]
                                                                                    at java.lang.Class.getConstructor(Class.java:528)
                                                                                    at java.lang.Class.getConstructor(Class.java:492)
                                                                                    at android.support.v7.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:502)
                                                                                    at android.support.v7.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:462)
                                                                                    at android.support.v7.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:483)
                                                                                    at android.support.v7.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:200)
                                                                                    at android.support.v7.view.SupportMenuInflater.inflate(SupportMenuInflater.java:122)
                                                                                    at org.hawkular.client.android.fragment.FavMetricsFragment.onCreateOptionsMenu(FavMetricsFragment.java:186)
                                                                                    at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2288)
                                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2984)
                                                                                    at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:328)
                                                                                    at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:363)
                                                                                    at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                                                    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
                                                                                    at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                                                    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
                                                                                    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-29 15:57:41.084 9192-9192/org.hawkular.client.android D/AndroidRuntime: Shutting down VM
                                                                           
                                                                           
                                                                           --------- beginning of crash
06-29 15:57:41.085 9192-9192/org.hawkular.client.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: org.hawkular.client.android, PID: 9192
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setOnQueryTextListener(android.support.v7.widget.SearchView$OnQueryTextListener)' on a null object reference
                                                                               at org.hawkular.client.android.fragment.FavMetricsFragment.onCreateOptionsMenu(FavMetricsFragment.java:190)
                                                                               at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2288)
                                                                               at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2984)
                                                                               at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:328)
                                                                               at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:363)
                                                                               at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                                               at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
                                                                               at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                                               at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
                                                                               at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-29 15:58:52.849 9192-9192/org.hawkular.client.android I/Process: Sending signal. PID: 9192 SIG: 9
```

**Comment by pg301** [comment]
@danielpassos It's a search view problem.

**Comment by KeenWarrior** [comment]
@pg301 Can you fix it?

**Comment by pg301** [comment]
@garg-anuj Sure! I will give you an update in some time.

**Comment by pg301** [comment]
@garg-anuj the code works fine. Earlier I was getting the same error then I updated google services and also made some changes in the gradle file.

**Comment by pg301** [comment]
@garg-anuj @danielpassos 
screenshot_1498837782
Here's a screenshot

**Comment by pg301** [comment]
@danielpassos @garg-anuj no need to update services only gradle changes will do.

**Comment by KeenWarrior** [comment]
@pg301 generally in such case where `minifyEnabled false` correct the app, we can deduce that `proguard` need additional setting. But for sake of removing the bottleneck from current work I think we should go with this solution and come back to `minifyEnabled true` later.

**Review by pg301 — APPROVED** [review]

**Pull request merged**
