### PR TITLE
Sectioned resources

### PR DESCRIPTION
**Pull request by arturdryomov**
This will allow to eliminate `ResourceTypesActivity` reducing screens count and, as a consequence, clicks count user needs to perform to access metrics. To do so I need #16 merged to avoid merge conflicts.

device-2015-06-19-084758

### CODE REVIEW

**Comment by danielpassos** [comment]
:eyes: (It means, I'm reviewing)

**Comment by danielpassos** [comment]
I know it's not related with it, but if I try run it without config push, the app crash. 

```
    java.lang.RuntimeException: Unable to create application org.hawkular.client.android.HawkularApplication: java.lang.IllegalArgumentException: URI is not absolute: placeholder
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: URI is not absolute: placeholder
            at java.net.URI.toURL(URI.java:1376)
            at org.jboss.aerogear.android.unifiedpush.gcm.AeroGearGCMPushRegistrar.<init>(AeroGearGCMPushRegistrar.java:106)
            at org.jboss.aerogear.android.unifiedpush.gcm.AeroGearGCMPushConfiguration.buildRegistrar(AeroGearGCMPushConfiguration.java:325)
            at org.jboss.aerogear.android.unifiedpush.gcm.AeroGearGCMPushConfiguration.buildRegistrar(AeroGearGCMPushConfiguration.java:31)
            at org.jboss.aerogear.android.unifiedpush.PushConfiguration.asRegistrar(PushConfiguration.java:92)
            at org.hawkular.client.android.push.PushClient.setUpPush(PushClient.java:50)
            at org.hawkular.client.android.HawkularApplication.setUpPush(HawkularApplication.java:51)
            at org.hawkular.client.android.HawkularApplication.onCreate(HawkularApplication.java:35)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
```

**Comment by arturdryomov** [comment]
Yep, apparently my checking of such situations is not really effective. I’ll fix that.

**Comment by danielpassos** [comment]
Landed at https://github.com/hawkular/hawkular-android-client/commit/37738d95bcbc2ad2d9c309eb6c8ac8b843c0a821

**Pull request closed without merging**
