### PR TITLE
Inventory Fixing part 4

### PR DESCRIPTION
**Pull request by pg301**
@garg-anuj I need your help in debugging. When I try getting data for any type of metric, it shows me that the metric.getValue returns null. Please can you check this.

### CODE REVIEW

**Comment by KeenWarrior** [comment]
@pg301 looking into it

**Comment by pg301** [comment]
@garg-anuj I think I debugged the error. I wasn't timestamping my start and end values while making the curl call and that was giving me empty buckets.

**Comment by pg301** [comment]
@pilhuhn We need to update our API documentation. http://www.hawkular.org/docs/rest/rest-metrics.html#GET__availability__id__stats mentions that this API return array of **data points**, but we get this as response https://paste.ubuntu.com/25151988/

**Comment by pg301** [comment]
@garg-anuj view value is not been written for some reason.  https://github.com/pg301/hawkular-android-client/blob/6e2ee34d7c920a268969749d7dc4743fb18b7fd2/mobile/src/main/java/org/hawkular/client/android/fragment/MetricAvailabilityFragment.java#L279 

This value is always null.

**Comment by KeenWarrior** [comment]
@pg301 progress in it is stuck?

**Pull request closed without merging**
